import java.rmi.RemoteException;
import java.net.*;
import java.rmi.*;
import java.awt.event.ActionEvent;
import java.io.*;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dagi
 */
// package ds_project;
public class calc_GUI extends javax.swing.JFrame {

   Double number1 = 0.0;
   Double number2 = 0.0;
   Double ans = 0.0;
    String snum2 = null;
    String snum1 = null;
    AddRem remobj;

    /**
     * Creates new form calc_GUI
     */
    public calc_GUI() {
        try {
            remobj = (AddRem) Naming.lookup("rmi://localhost/AddRem");
        } catch (Exception e) {
            System.out.print(e);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        subtract = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        result = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mini Calculator");
        jLabel1.setToolTipText("");

        jLabel2.setText("Number 1");

        jLabel3.setText("Number 2");

        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);

            }
        });

        add.setText("Add(+)");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {

                addActionPerformed(evt);
                snum1 = num1.getText();
                snum2 = num2.getText();

              
                try{
                    number1 = Double.parseDouble(snum1);
                    number2 = Double.parseDouble(snum2);
            
               
                    ans = remobj.add(number1, number2);
                     jTextArea1.setText(ans + " ");
              
         
              
 

                   
                   
                   
                }catch(Exception e){
                    jTextArea1.setText(e + " ");
                }

               

            }
        });

        subtract.setText("Subtract(-)");
        subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                subtractActionPerformed(evt);
                snum1 = num1.getText();
                snum2 = num2.getText();

              
                try{
                    number1 = Double.parseDouble(snum1);
                    number2 = Double.parseDouble(snum2);
            
             
                    ans = remobj.sub(number1, number2);
                     jTextArea1.setText(ans + " ");
             
              
 

                   
                   
                   
                }catch(Exception e){
                    jTextArea1.setText(e + " ");
                }

            }
        });

        multiply.setText("Multiply(*)");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
                snum1 = num1.getText();
                snum2 = num2.getText();

              
                try{
                    number1 = Double.parseDouble(snum1);
                    number2 = Double.parseDouble(snum2);
            
            
                    ans = remobj.mult(number1, number2);
                     jTextArea1.setText(ans + " ");
         
              
 

                   
                   
                   
                }catch(Exception e){
                    jTextArea1.setText(e + " ");
                }

            }
        });

        divide.setText("Divide(/)");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
              
                snum1 = num1.getText();
                snum2 = num2.getText();
              
                try{
                  
                    number1 = Double.parseDouble(snum1);
                    number2 = Double.parseDouble(snum2);
            
              
                    ans = remobj.div(number1, number2);
                    if(ans == 0.0){
                        jTextArea1.setText("error");
                    }else
                     jTextArea1.setText(ans + " ");
              
              
 

                   
                   
                   
                }catch(Exception e){
                    jTextArea1.setText(e + " ");
                }

            }

            private void divideActionPerformed(ActionEvent evt) {
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        result.setViewportView(jTextArea1);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jLabel1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup().addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2).addComponent(jLabel3))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup().addComponent(add)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(subtract)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(multiply)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(divide)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
                .addGroup(layout.createSequentialGroup().addGap(35, 35, 35)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 289,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup()
                .addComponent(
                        jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel2)
                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(add)
                        .addComponent(subtract).addComponent(multiply).addComponent(divide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_num1ActionPerformed

    private void addActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_addActionPerformed

    private void subtractActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_subtractActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_subtractActionPerformed

    private void multiplyActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_multiplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
           

        try {
            for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (final ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton divide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton multiply;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JScrollPane result;
    private javax.swing.JButton subtract;
    // End of variables declaration//GEN-END:variables
}
